### ISSUE TITLE
1 - Conhecendo o Git e GitHub

### ISSUE THREAD

**Issue by AnnyCaroline** [AnnyCaroline/informatica-para-trabalho#1]
Utilizaremos este repositório para todas as tarefas da disciplina. Essa primeira tarefa servirá como uma introdução para o Git e GitHub, e e fará com que vocês se familiarizem com a forma com que os trabalhos deverão ser entregues.

O que deve ser feito nesta tarefa:
- Criem uma conta no GitHub
- Criem um novo repositório
- Alterem o README.md pela interface web. O seu README deverá conter:
    - Uma lista
    - Seu(s) nome(s) - completos
    - Um título
    - E um trecho de código
- O primeiro commit deverá se chamar "Update README.md"
- Deixem um comentário aqui nessa issue contendo o link do repositório

**Comment by alygames** [comment]
https://github.com/alygames/pollyne-dias/blob/d1f6ef9edb6d8f2945d15f33c1cdec9d7402b63a/README.md

**Comment by ArielBr2006** [comment]
https://github.com/ArielBr2006/Informatica-do-Trabalho1/blob/main/README.md

**Comment by LuanLuis1121232** [comment]
https://github.com/LuanLuis1121232/Luan-Luis-e-Saboia/edit/main/README.md

Pedro Saboia, Luan Gama e Luis Guilherme; 
Turma 1103

**Comment by luizfelipecardoso** [comment]
https://github.com/luizfelipecardoso/new-repository

**Comment by Art-Fernandes** [comment]
https://github.com/Art-Fernandes/Arthur-Fernandes-Coutinho/blob/main/README.md

**Comment by Madribea** [comment]
https://github.com/Madribea/trabalho/blob/main/README.md
